version: '3'

services:
  pulsar:
    image: apachepulsar/pulsar:2.9.1
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
#      - "8080:8080"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: localtest
      POSTGRES_USER: pgtest
      POSTGRES_PASSWORD: pgtest
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pulsardata:
  pulsarconf:
  postgresdata:
